name: Setup and Run Process

on:
  push:
    branches:
      - master

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Clone ArknightsGameData repository
      run: |
        git clone https://github.com/Kengxxiao/ArknightsGameData ./gamedata_rep

    - name: Generate gamedata.json
      run: |
        GAMEDATA_ABS_PATH=$(realpath ./gamedata_rep)
        echo "{\"gamedata\": \"${GAMEDATA_ABS_PATH}/zh_CN/gamedata\"}" > ./config/gamedata.json

    - name: Generate baidu.json from Action Secrets
      run: |
        echo "{\"BAIDU_JSON\": \"${{ secrets.BAIDU_JSON }}\"}" > ./config/baidu.json

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the batch file
      run: |
        ./run.bat
