name: Setup and Run Process

on:
  push:
    branches:
      - master

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Generate gamedata.json
      run: |
        GAMEDATA_ABS_PATH=$(realpath ./gamedata_rep)
        echo "{\"gamedata\": \"${GAMEDATA_ABS_PATH}/zh_CN/gamedata\"}" > ./config/gamedata.json

    - name: Generate baidu.json from Action Secrets
      run: |
        echo "${{ secrets.BAIDU_JSON }}" > ./config/baidu.json
        
    - name: Output JSON files content (for testing)
      run: |
        echo "Contents of gamedata.json:"
        cat ./config/gamedata.json
        echo "Contents of baidu.json:"
        cat ./config/baidu.json
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python scripts
      run: |
        python gen_attr.py --single_file
                
    - name: Clone ArknightsGameData repository
      run: |
        git clone https://github.com/Kengxxiao/ArknightsGameData ./gamedata_rep

